spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # Routes principales
        - id: user-auth
          uri: http://localhost:8019
          predicates:
            - Path=/api/auth/**
        - id: user-users
          uri: http://localhost:8019
          predicates:
            - Path=/api/users/**
        - id: diplomas-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/diplomes/**
        - id: competencies-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/competences/**

        # Routes Swagger
        - id: user-api-docs
          uri: http://localhost:8019
          predicates:
            - Path=/user/v3/api-docs/**
          filters:
            - RewritePath=/user/v3/api-docs(?<remaining>.*), /v3/api-docs$\{remaining}
        - id: diplomas-api-docs
          uri: http://localhost:8082
          predicates:
            - Path=/diplomas/v3/api-docs/**
          filters:
            - RewritePath=/diplomas/v3/api-docs(?<remaining>.*), /v3/api-docs$\{remaining}
        - id: competencies-api-docs
          uri: http://localhost:8020
          predicates:
            - Path=/competencies/v3/api-docs/**
          filters:
            - RewritePath=/competencies/v3/api-docs(?<remaining>.*), /v3/api-docs$\{remaining}

server:
  port: 8003

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user/v3/api-docs
      - name: Diplomas Service
        url: /diplomas/v3/api-docs
      - name: Competencies Service
        url: /competencies/v3/api-docs
  api-docs:
    enabled: true